#!/usr/bin/env bash

if [[ -n "${OFICINA_DB_SCRIPT_DEFAULTS_SH_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi

OFICINA_DB_SCRIPT_DEFAULTS_SH_LOADED=true

OFICINA_PROJECT_NAME="${OFICINA_PROJECT_NAME:-oficina}"
OFICINA_ENVIRONMENT_NAME="${OFICINA_ENVIRONMENT_NAME:-${OFICINA_ENVIRONMENT:-lab}}"
OFICINA_ENVIRONMENT="${OFICINA_ENVIRONMENT:-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_SECRET_PREFIX="${OFICINA_SECRET_PREFIX:-${OFICINA_PROJECT_NAME}/${OFICINA_ENVIRONMENT_NAME}}"

OFICINA_AWS_REGION="${OFICINA_AWS_REGION:-${AWS_REGION:-us-east-1}}"
OFICINA_SHARED_INFRA_NAME="${OFICINA_SHARED_INFRA_NAME:-${SHARED_INFRA_NAME:-eks-${OFICINA_ENVIRONMENT_NAME}}}"
OFICINA_EKS_CLUSTER_NAME="${OFICINA_EKS_CLUSTER_NAME:-${EKS_CLUSTER_NAME:-eks-${OFICINA_ENVIRONMENT_NAME}}}"

OFICINA_TERRAFORM_ENV_DIR="${OFICINA_TERRAFORM_ENV_DIR:-${REPO_ROOT:-}/terraform/environments/${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_TF_STATE_KEY="${OFICINA_TF_STATE_KEY:-${OFICINA_SECRET_PREFIX}/database/terraform.tfstate}"

OFICINA_DB_IDENTIFIER="${OFICINA_DB_IDENTIFIER:-${OFICINA_PROJECT_NAME}-postgres-${OFICINA_ENVIRONMENT_NAME}}"
OFICINA_DB_NAME="${OFICINA_DB_NAME:-app}"
OFICINA_DB_USERNAME="${OFICINA_DB_USERNAME:-oficina_master}"
OFICINA_APP_DB_USER="${OFICINA_APP_DB_USER:-oficina_app}"
OFICINA_DB_SSLMODE="${OFICINA_DB_SSLMODE:-require}"

OFICINA_DB_APP_SECRET_ID="${OFICINA_DB_APP_SECRET_ID:-${OFICINA_SECRET_PREFIX}/database/app}"
OFICINA_DB_K8S_SECRET_NAME="${OFICINA_DB_K8S_SECRET_NAME:-${OFICINA_PROJECT_NAME}-database-env}"
OFICINA_K8S_NAMESPACE="${OFICINA_K8S_NAMESPACE:-default}"

OFICINA_DB_IMPORT_FILE="${OFICINA_DB_IMPORT_FILE:-sql/import.sql}"
OFICINA_DB_MIGRATIONS_DIR="${OFICINA_DB_MIGRATIONS_DIR:-sql/migrations}"
OFICINA_FLYWAY_DOCKER_IMAGE="${OFICINA_FLYWAY_DOCKER_IMAGE:-redgate/flyway:12.4-alpine}"
OFICINA_PSQL_DOCKER_IMAGE="${OFICINA_PSQL_DOCKER_IMAGE:-postgres:16-alpine}"
